### ISSUE TITLE
how to have zones in separate files?

### ISSUE THREAD

**Issue by mikysal78** [nishiki/ansible-role-bind#14]
multiple zones in separate files?
dnssec key in separate files?

**Comment by BenjamenMeyer** [comment]
So I have something like:
```
bind_zones:
   'dnsname':
      ns_primary: ns.mydomain
      ...
   records:
      - { name: ... }
   'yetanotherdnsname':
      ns_primary: ns.mydomain
      ...
   records:
      - { name: ... }
   'dnsname':
      ns_primary: ns.mydomain
      ...
   records:
      - { name: ... }
```
and they all come out as:
```
/etc/bind/zones/<zone>/db
/etc/bind/zones/<zone>/db.signed
...
```

does that answer your question?
